### ISSUE TITLE
Hazard Analysis Peer Review

### ISSUE THREAD

**Issue by TimChoy** [arkinmodi/project-sayyara#169]
**DUE**: Oct 21, 2022 + 2 days of grace period

**Team to Review**: Team 6, Board Gamers
**Repository**: https://github.com/Dorps/aiboardgame

- Create at least 5 "deep" issues
    - Not typos or formatting mistakes
    - Focus on observations based on the Hazard Analysis rubric
- Issues are prefixed with `Team3 Review`:
- Issues have the label `Review-HazA-Team03`
- Tag the TA grading Team 6

**Comment by arkinmodi** [comment]
1. The requirements are not phrased as statements that the system shall do
2. Conflicting Scope
    - "Physical Computer" is listed under the system boundaries and out of scope sections. If you are not in control of the "Physical Computer", we think you should exclude it from your boundaries.
3. The "Training Model" Recommended Actions do not cover all the Causes of Failure
4. Missing Assumptions
    - From the slides, an example assumption: "the operator of your machine isn’t intentionally trying to misuse it".
    - We think it ie better to state what you assume the "Physical Computer" is capable of
5. Failures caused by user actions are not failures
    - You define a hazard as: "A hazard for our AI-based game simulation engine will be any threat, vulnerability, system failure, or potential errors that our system is susceptible to." You also state: "... user error will be considered out of the scope for this document.". However in your FMEA table, you list user actions as causes of failure. You definitions conflict with this therefore, this should not be a cause of failure.

**Comment by arkinmodi** [comment]
Peer Review Issues:
- https://github.com/Dorps/aiboardgame/issues/13
- https://github.com/Dorps/aiboardgame/issues/14
- https://github.com/Dorps/aiboardgame/issues/15
- https://github.com/Dorps/aiboardgame/issues/16
- https://github.com/Dorps/aiboardgame/issues/17
- https://github.com/Dorps/aiboardgame/issues/18
- https://github.com/Dorps/aiboardgame/issues/19
- https://github.com/Dorps/aiboardgame/issues/20
