### ISSUE TITLE
Technology and Tools

### ISSUE THREAD

**Issue by arkinmodi** [arkinmodi/project-sayyara#19]
**Report:** Development Plan

**Included Sections**
- Technology
- Coding Standard

**Comment by arkinmodi** [comment]
### Some Questions I Had
1. Are there any hard requirements that you have on the tech stack or architecture? Is there anything you would prefer? I know you have previously stated that we can do whatever we desired, but since you are the supervisor/client, we want to make sure your desires are included in our decisions.
    - From previous discussions, it sounded like a PWA is a hard requirement, and a microservice architecture is something desired.
    - Do you want a dedicated/separated backend? For example, if we use Next.js, this framework has an integrated frontend and backend.
    - Examples areas: languages, frameworks, databases (type and/or provider), authentication methods, cloud providers, API standard, etc.
2. The problem description says that you would like it to be deployed on the cloud. We plan to add this as a stretch goal. How exactly do you want to run this in the cloud? Do you want dedicated servers or serverless? Since you will be the one in the end actually running this, having some direction on what you are visualizing and your cloud budget is important to us.
3. Do you have an overall budget in mind? This can help influence our tech stack decisions (and possible changes later in the course).

**Comment by nabsofken** [comment]
@arkinmodi great questions.
1. The only hard requirement is to build a PWA with the following main features: Appointments, Quotes, work orders, Services, and profiles for employees and the shop owner (I will share a Miro board defining the MVP). The rest are not hard requirements.
2. We can ignore the deployment to the cloud requirement. Local build(s) are fine with instructions
3. I am open to purchasing UI themes, and icon packs if needed. If there is anything else we can discuss
