### ISSUE TITLE
[VnV Report] Verification and Validation Report

### ISSUE THREAD

**Issue by arkinmodi** [arkinmodi/project-sayyara#432]
**[Verification and Validation Report](https://github.com/arkinmodi/project-sayyara/blob/main/docs/VnVReport/VnVReport.pdf) | [Rubric](https://gitlab.cas.mcmaster.ca/courses/capstone/-/blob/main/Rubrics/VnVReport.xlsx) | [Examples](https://gitlab.cas.mcmaster.ca/courses/capstone/-/tree/main/SamplesOfStudentWork/VnVReport)**

**Reference Slides**
- [Lecture 11 - Revision 0, Verification and Validation Report](https://gitlab.cas.mcmaster.ca/courses/capstone/-/blob/main/Lectures/L11_Rev0_VnVReport/Rev0_VnVReport.pdf)

### Sections
**Introduction**
- [x] #440

**Documentation Evaluation**
- [x] #627
- [x] #628
- [x] #629
- [x] #630

**Functional Requirements Evaluation**
- [x] #441
- [x] #442
- [x] #443
- [x] #444
- [x] #445
- [x] #446
- [x] #447
- [x] #448
- [x] #449

**Nonfunctional Requirements Evaluation**
- [x] #450
- [x] #451
- [x] #452
- [x] #453
- [x] #454
- [x] #455
- [x] #456
- [x] #457

**Comparison to Existing Implementation**
N/A

**Unit Testing**
- [x] #459
- [x] #578
- [x] #579
- [x] #580
- [x] #581
- [x] #582
- [x] #583

**Changes Due to Testing**
- [x] #460

**Automated Testing**
- [x] #461

**Trace to Requirements**
- [x] #462

**Trace to Modules**
- [x] #463

**Code Coverage Metrics**
- [x] #464

**Appendix**
- [x] #458

**Polishing**
- [x] #434

## Meetings
- #431
- #496
- #509
- #538
- #552

**Comment by LeonSo7** [comment]
Usability Survey:
1. Were there any bugs or issues that you ran into?
2. What did you like the most or what stood out for you while using the application?
3. Please share what you’d like to change on our website.
4. How likely are you to recommend our application based on the user experience to others on a scale of 1 to 10?
5. Please share any challenges you experienced while using our application.
6. Please share any comments or suggestions you may have.
7. Which user accounts did you test with? (i.e., CUSTOMER, EMPLOYEE, OR SHOP OWNER)?
8. Was the website intuitive, easy to learn to use and navigate?
9. When you made a mistake navigating or using the application, was it easy to recover?
10. Were the fonts and colours used easy to read? If not, explain.
11. What device (e.g., brand, model, type) were you using to test? Did everything work as expected? If not, what did not work as expected?
