### ISSUE TITLE
Software Requirements Specification

### ISSUE THREAD

**Issue by arkinmodi** [arkinmodi/project-sayyara#48]
**[Report](https://github.com/arkinmodi/project-sayyara/blob/main/docs/SRS/SRS.pdf) | [Rubric](https://gitlab.cas.mcmaster.ca/courses/capstone/-/blob/main/Rubrics/SRS.xlsx) | [Examples](https://gitlab.cas.mcmaster.ca/courses/capstone/-/tree/main/SamplesOfStudentWork/SRS)**

**Reference Slides**
- [Lecture 3 - Requirements](https://gitlab.cas.mcmaster.ca/courses/capstone/-/blob/main/Lectures/L03_Requirements/Requirements.pdf)
- [Lecture 4 - Requirements Continued](https://gitlab.cas.mcmaster.ca/courses/capstone/-/blob/main/Lectures/L04_ReqContinued/ReqContinued.pdf)
- [Lecture 5 - Requirements Continued Continued](https://gitlab.cas.mcmaster.ca/courses/capstone/-/blob/main/Lectures/L05_ReqContdContd/ReqContdContd.pdf)
- [Lecture 6 - Project Management Advice and Licensing (Slide 20)](https://gitlab.cas.mcmaster.ca/courses/capstone/-/blob/main/Lectures/L06_ProjectManagementAdvice/ProjectManagementAdvice.pdf)

Preconditions:
- [x] #77 

Deliverables:
Project Drivers
- [x] #60 
- [x] #61 
- [x] #62 
- [x] #111

Functional Requirements
- [x] #63 
- [x] #64 
- [x] #65 
- [ ] #66 
- [x] #67 
- [x] #68 
- [x] #69 
- [x] #70 
- [x] #71 
- [x] #72 
- [x] #73 

Non-Functional Requirements
- [x] #74 

Project Issues
- [x] #75

Appendix
- [x] #92 

Polishing
- [x] #76

**Comment by TimChoy** [comment]
Project Drivers
- [ ] #60
