### ISSUE TITLE
[Rev 1 Docs] [VnV Plan] Functional Requirements Unit Tests - Shop Module

### ISSUE THREAD

**Issue by arkinmodi** [arkinmodi/project-sayyara#560]
**Report:** Verification and Validation Plan
**Section Number:** 6.2

### Rubric Sections
**VnV Report Rubric**
- VnV Report Matches VnV Plan

**Final Doc Rubric**
- Update VnV Plan and Report

**Comment by LeonSo7** [comment]
Completed unit testing for shop profile portion of Shop Module:
* Tests for `get shop by Id`
* Tests for `update shop`

Remaining portion is @TimChoy's shop lookup
