### ISSUE TITLE
[VnV Report] Unit Testing - Shop Module

### ISSUE THREAD

**Issue by arkinmodi** [arkinmodi/project-sayyara#583]
## Content

- Unit Testing

## Rubric Sections

- Content
- Spelling and grammar and style
- VnV Report Matches VnV Plan

**Comment by LeonSo7** [comment]
Completed unit testing for shop profile portion of Shop Module:
* Tests for `get shop by Id`
* Tests for `update shop`

Remaining portion is @TimChoy's shop lookup
